# Generated by Django 5.1.15 on 2026-05-24 23:40

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlays', '0014_ocr_feedback_compact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrscanfeedback',
            name='was_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parlay',
            name='creator_nickname',
            field=models.CharField(default='HOST', max_length=64),
        ),
        migrations.AlterField(
            model_name='parlay',
            name='host_code',
            field=models.CharField(blank=True, db_index=True, help_text='Alphanumeric code for the host to find and manage this parlay (expires after 72 hours).', max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='parlay',
            name='host_code_expires_at',
            field=models.DateTimeField(blank=True, help_text='After this time the parlay is unavailable (public and host pages).', null=True),
        ),
        migrations.AlterField(
            model_name='parlay',
            name='split_offered_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Percent of wager friends may claim in total (host keeps the rest).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
    ]
