# Generated by Django 5.1.15 on 2026-05-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlays', '0015_alter_ocrscanfeedback_was_edited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parlay',
            name='slug',
            field=models.SlugField(editable=False, help_text='Public URL segment, e.g. jordans-parlay-3legs-x7k2m.', max_length=96, unique=True),
        ),
    ]
